Repository AY2425S1-CS2103T-T17-3/tp, pull requests merged in 2024-10, with the labels that each got.

#24 Update site-wide settings
  docs/_markbind/layouts/default.md
Labels: type.Task

#41 Add product command until LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddProductCommand.java
  src/main/java/seedu/address/logic/parser/AddProductCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/product/Product.java
  src/main/java/seedu/address/model/product/ProductName.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#134 Update add-product command to ensure one-to-one relationship between product and supplier
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddProductCommand.java
  src/main/java/seedu/address/logic/commands/AssignProductCommand.java
  src/main/java/seedu/address/model/product/Product.java
  src/test/java/seedu/address/logic/commands/AssignProductCommandTest.java
  src/test/java/seedu/address/testutil/ProductBuilder.java
Labels: type.Enhancement
